In [1]:
#설정변경코드
#변수 명이 두번 이상 출력되어도 모두 콘솔에서 보여줄 것
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

# InteractiveShell.ast_node_interactivity : 'all' | 'last' | 'last_expr' | 'none' (기본값은 'last_expr')

In [2]:
#모듈 import
import numpy as np
import pandas as pd

In [3]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2000002],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율":[0.0283, 0.0163, 0.0982,0.0141]
}
columns = ['지역','2000','2005','2010','2015', '2010-2015 증가율']
index = ['서울','부산','인천','대구']
df3 = pd.DataFrame(data, index=index, columns=columns)
df3

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141

### DF의 행 추가
- pd의 데이터프레임 인덱서(loc) 사용
- pd.concat() 사용 => 추가하고자 하는 행 data를 df로 새로 생성 후 결합
- **df의 열 추가 설명 노트 1-1-_1에 있음**

In [4]:
# df3에 광주행을 추가 => loc 인덱서 이용
df3.loc['광주'] = ['호남권',2470000,2456000,2453000,2460000,1.00]
df3

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141
광주  호남권  2470000  2456000  2453000  2460000         1.0000

In [5]:
# df3에 전주행을 추가 => concate() 함수를 이용
# 추가하려고 하는 행 data를 df로 생성 -> concat() 로 합치기

temp = pd.DataFrame([['호남권',2470000,2456000,2453000,2460000,1.00]],
                   index = ['전주'])
temp

0        1        2        3        4    5
전주  호남권  2470000  2456000  2453000  2460000  1.0

In [6]:
pd.concat([df3, temp])  # column 명이 달라서 새로운 열을 추가하는 형태로 결합

지역       2000       2005       2010       2015  2010-2015 증가율    0  \
서울  수도권  9853972.0  9762546.0  9631482.0  9904312.0         0.0283  NaN   
부산  경상권  3655437.0  3512547.0  3393191.0  3448737.0         0.0163  NaN   
인천  수도권  2466338.0  2517680.0  2632035.0  2890451.0         0.0982  NaN   
대구  경상권  2473990.0  2456016.0  2000002.0  2466052.0         0.0141  NaN   
광주  호남권  2470000.0  2456000.0  2453000.0  2460000.0         1.0000  NaN   
전주  NaN        NaN        NaN        NaN        NaN            NaN  호남권   

            1          2          3          4    5  
서울        NaN        NaN        NaN        NaN  NaN  
부산        NaN        NaN        NaN        NaN  NaN  
인천        NaN        NaN        NaN        NaN  NaN  
대구        NaN        NaN        NaN        NaN  NaN  
광주        NaN        NaN        NaN        NaN  NaN  
전주  2470000.0  2456000.0  2453000.0  2460000.0  1.0

In [7]:
temp.columns = df3.columns
temp

지역     2000     2005     2010     2015  2010-2015 증가율
전주  호남권  2470000  2456000  2453000  2460000            1.0

In [8]:
pd.concat([df3,temp])

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141
광주  호남권  2470000  2456000  2453000  2460000         1.0000
전주  호남권  2470000  2456000  2453000  2460000         1.0000

#### 행이나 열을 삭제할 때 사용하는 함수
- drop() 함수 사용
- drop(index=[삭제할 행 인덱스])
- drop(columns=[삭제할 컬렴명])
- 삭제한 결과를 반환만 해주기 때문에 원본에는 바로 반영되지 않는다
- 완전히 삭제하려면 (원본에 반영하려면)
    - drop(inplace=True) 파라미터를 입력해주면 된다.

In [9]:
df3

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141
광주  호남권  2470000  2456000  2453000  2460000         1.0000

In [10]:
df3.drop(index=['광주']) # 원본 반영하지 않음
df3.drop(index=['광주','대구'])
df3  # 원본에 반영되지 않은 것 확인 가능

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982
대구  경상권  2473990  2456016  2000002  2466052         0.0141
광주  호남권  2470000  2456000  2453000  2460000         1.0000

In [11]:
df3.drop(index=['광주','대구'], inplace=True) # 원본에 반영해주는 파라미터
# 대입연산이 진행되므로 삭제 후 결과를 반환하지 않는다.( 인터프리터에 )
df3 # 원본에 반영됨

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982

In [12]:
# 열 삭제
df3.drop(columns=['2010-2015 증가율']) # 동일하게 inplace 파라미터에 따라 원본반영 여부 결정
df3

지역     2000     2005     2010     2015
서울  수도권  9853972  9762546  9631482  9904312
부산  경상권  3655437  3512547  3393191  3448737
인천  수도권  2466338  2517680  2632035  2890451

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982

In [13]:
# drop(axis= 0 또는 1 ) : 0은 행을 지칭, 1은 열을 지칭
df3.drop(['서울'],axis=0)   # 원본 반영 안됨
df3.drop(['지역'],axis=1)   # 원본 반영 안됨
df3

지역     2000     2005     2010     2015  2010-2015 증가율
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982

2000     2005     2010     2015  2010-2015 증가율
서울  9853972  9762546  9631482  9904312         0.0283
부산  3655437  3512547  3393191  3448737         0.0163
인천  2466338  2517680  2632035  2890451         0.0982

지역     2000     2005     2010     2015  2010-2015 증가율
서울  수도권  9853972  9762546  9631482  9904312         0.0283
부산  경상권  3655437  3512547  3393191  3448737         0.0163
인천  수도권  2466338  2517680  2632035  2890451         0.0982

### pandas 데이터처리 및 변환관련 함수

#### 데이터 개수 세기
- 가장 간단한 분석은 개수를 세기 이다. count()함수 이용
    - NaN값은 세지 않는다.

In [14]:
# s.count()

### 데이터 프레임에 count()함수 적용하기
- 각 열마다 데이터 개수를 세기때문에 누락된 부분을 찾을 때 유용


#### 난수 발생시켜 dataframe 생성
- 난수 seed(값)라는 함수를 사용할 수 있음
- seed의 의미 : 난수 알고리즘에서 사용하는 기본 값으로
    - 시드값이 같으면 동일한 난수가 발생함
- 계속 변경되는 난수를 받고 싶으면 함수등을 이용해서 시드값이 매번 변하게 작업해야 함. Time.tiem()

In [15]:
np.random.randint(5)  # 정수 0~4 까지의 숫자중 랜덤하게 추출
np.random.randint(5, size=4)

0

array([3, 2, 0, 1])

In [16]:
np.random.seed(3)
np.random.randint(5, size=4)
# 시드 값은 한번만 적용하기 때문에 다른 인터프리터에서는 seed 값이 적용되지 않음

array([2, 0, 1, 3])

In [17]:
# seed값은 난수 발생시마다 설정해야 함
np.random.randint(5, size=4)

array([0, 0, 0, 3])

In [18]:
import time
# time.time()
np.random.seed(int(time.time()))
np.random.randint(5, size=4)

array([0, 4, 0, 2])

In [19]:
np.random.seed(3)  #seed 값 고정 => 동일한 난수를 만들기 위해
df1 = pd.DataFrame(np.random.randint(5,size=(4,4)))
df1.iloc[2,3] = np.nan
df1

0  1  2    3
0  2  0  1  3.0
1  0  0  0  3.0
2  2  3  1  NaN
3  2  0  4  4.0

In [20]:
# 각 열의 data 개수 반환
# 3열은 3개의 data 반환되었으므로 결측치가 있다는 것 파악 가능
df1.count()

0    4
1    4
2    4
3    3
dtype: int64

##### count 함수 사용 예제

- 타이타닉 승객 데이터 사용
    - seaborn 패키지 내에 data로 존재
    - 데이터셋 읽어오기 : 패키지명.load_dataset("data명")

In [21]:
import seaborn as sns  # 그래프 패키지, 시각화

# 타이타닉 승객데이터를 load 해서 사용
titanic = sns.load_dataset('titanic')
titanic.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [22]:
titanic.shape

(891, 15)

In [23]:
titanic.count()
# 대부분의 열이 891개의 원소가 있는데 반해
# age는 714개, deck는 203개, embarked 889개의 원소 - 결측치가 있는 열이라고 파악 가능
# age열과 embarked 열은 결측치를 대체해서 사용해도 무방할 것 같음
# deck는 전체 행에 비해 결측치가 너무 많음 => 해당 열은 drop 하는게 좋을 것 같음

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [24]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


###  카테고리 값 세기
- 시리즈의 값이 정수,문자열 등 카테고리 값인 경우에
- 시리즈.value_counts()메서드를 사용해 각각의 값이 나온 횟수를 셀 수 있음
- 파라미터 normalize=True 를 사용하면 각 값 및 범주형 데이터의 비율을 계산
    - 시리즈.value_counts(normalize=True)

In [25]:
np.random.seed(1)
s2 = pd.Series(np.random.randint(6,size=100))
s2.head(10)
s2.tail(10)

0    5
1    3
2    4
3    0
4    1
5    3
6    5
7    0
8    0
9    1
dtype: int32

90    3
91    0
92    0
93    5
94    5
95    4
96    5
97    2
98    4
99    3
dtype: int32

In [26]:
s2.value_counts() # 0,1,2,3,4,5 의 값이 몇번 나왔는지 count
s2.value_counts(normalize=True)  # 각 빈도의 비율 반환

1    22
0    18
4    17
5    16
3    14
2    13
dtype: int64

1    0.22
0    0.18
4    0.17
5    0.16
3    0.14
2    0.13
dtype: float64

##### 범주형 데이터에 value_counts() 함수 적용
- 범주형 데이터 : 관측 결과가 몇개의 범주 또는 항목의 형태로 나타나는 자료
    - ex. 성별(남,여), 선호도(좋다, 보통, 싫다), 혈액형(A,B,O,AB) 등

In [27]:
# 제공되는 타이타닉 승객 중 생존자수와 사망자수를 확인
# alive 열은 생존여부가 yes 또는 no 로 표시되어있음
titanic['alive'].dtype  # dtype('O') 는 오브젝트라는 뜻임
titanic['alive'].value_counts() # 사망자 / 생존자 수
titanic['alive'].value_counts(normalize=True) * 100  # 사망자와 생존자의 비율 

dtype('O')

no     549
yes    342
Name: alive, dtype: int64

no     61.616162
yes    38.383838
Name: alive, dtype: float64

In [28]:
titanic['sex'].value_counts()
titanic['sex'].value_counts(normalize=True)*100

male      577
female    314
Name: sex, dtype: int64

male      64.758698
female    35.241302
Name: sex, dtype: float64

##### 데이터프레임에  value_counts()  함수 사용


- 행을 하나의 value로 설정하고 동일한 행이 몇번 나타났는지 반환
- 행의 경우가 인덱스로 개수된 값이 value로 표시되는 Series 반환

In [29]:
titanic[['sex','alive']].head(2)

sex alive
0    male    no
1  female   yes

In [30]:
titanic[['sex','alive']].value_counts() # 시리즈 형태로 반환
type(titanic[['sex','alive']].value_counts())
titanic[['sex','alive']].value_counts().index
titanic[['sex','alive']].value_counts().values
# value_counts를 하면 df 형태가 아니라 다중 인덱스로 이루어진 시리즈로 반환 되는 것을 기억

sex     alive
male    no       468
female  yes      233
male    yes      109
female  no        81
dtype: int64

pandas.core.series.Series

MultiIndex([(  'male',  'no'),
            ('female', 'yes'),
            (  'male', 'yes'),
            ('female',  'no')],
           names=['sex', 'alive'])

array([468, 233, 109,  81], dtype=int64)

In [31]:
pd.DataFrame(titanic[['sex','alive']].value_counts())
pd.DataFrame(titanic[['sex','alive']].value_counts()).loc['male']

0
sex    alive     
male   no     468
female yes    233
male   yes    109
female no      81

0
alive     
no     468
yes    109

### 정렬함수 -데이터 정렬 시 사용
- sort_index() : 인덱스를 기준으로 정렬
- sort_value() : 데이터 값을 기준으로 정렬
- 파라미터 : ascending = True / False (오름차순/내림차순) => 오름차순정렬 적용 유/무


#### 시리즈 정렬

In [32]:
#예제 시리즈
s2

0     5
1     3
2     4
3     0
4     1
     ..
95    4
96    5
97    2
98    4
99    3
Length: 100, dtype: int32

In [33]:
s2.value_counts() # 반환 결과는 빈도값을 기준으로 내림차순 정렬된 결과

1    22
0    18
4    17
5    16
3    14
2    13
dtype: int64

In [34]:
s2.value_counts().sort_index() # index 값을 기준으로 오름차순 정렬

0    18
1    22
2    13
3    14
4    17
5    16
dtype: int64

In [35]:
s2.value_counts().sort_index(ascending=False) # index 값을 기준으로 내림차순 정렬

5    16
4    17
3    14
2    13
1    22
0    18
dtype: int64

In [36]:
s2.value_counts().sort_values() # value_counts()한 결과 빈도값을 기준으로 오름차순 정렬

2    13
3    14
5    16
4    17
0    18
1    22
dtype: int64

In [37]:
s2.value_counts().sort_values(ascending=False)
# value_counts()한 결과 빈도값을 기준으로 내림차순 정렬

1    22
0    18
4    17
5    16
3    14
2    13
dtype: int64

### 데이터 프레임 정렬

- df.sort_values() : 특정열 값 기준 정렬
    - 데이터프레임은 2차원 배열과 동일하기 때문에
        - 정렬시 기준열을 줘야 한다. by 인수 사용 : 생략 불가
        - by = 기준열, by=[기준열1,기준열2]
    - 오름차순/내림차순 : ascending = True/False (생략하면 오름차순)
- df.sort_index() : DF의 INDEX 기준 정렬
    - 오름차순/내림차순 : ascending = True/False (생략하면 오름차순)

In [38]:
df1

0  1  2    3
0  2  0  1  3.0
1  0  0  0  3.0
2  2  3  1  NaN
3  2  0  4  4.0

In [39]:
# df1.sort_values()
# TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'

In [40]:
df1.sort_values(by=[0])

0  1  2    3
1  0  0  0  3.0
0  2  0  1  3.0
2  2  3  1  NaN
3  2  0  4  4.0

In [41]:
df1.sort_values(by=[0,1])

0  1  2    3
1  0  0  0  3.0
0  2  0  1  3.0
3  2  0  4  4.0
2  2  3  1  NaN

In [42]:
df1.sort_values(by=[0,1], ascending=False)

0  1  2    3
2  2  3  1  NaN
0  2  0  1  3.0
3  2  0  4  4.0
1  0  0  0  3.0

In [43]:
df = pd.DataFrame({'num_legs': [2, 4, 4, 6],
                   'num_wings': [2, 0, 0, 0]},
                  index=['falcon', 'dog', 'cat', 'ant'])
df

num_legs  num_wings
falcon         2          2
dog            4          0
cat            4          0
ant            6          0

- 데이터프레임의 index를 기준으로 정렬

In [44]:
df.sort_index()
df.sort_index(ascending=False)

num_legs  num_wings
ant            6          0
cat            4          0
dog            4          0
falcon         2          2

num_legs  num_wings
falcon         2          2
dog            4          0
cat            4          0
ant            6          0

### 행/열 합계
- df.sum() 함수 사용
- 행과 열의 합계를 구할때는 sum(axis=0/1) - axis는 0이 기본


- 각 열의 모든 행의 합계를 구할때는 sum(axis=0)
- 각 행의 모든 열의 합계를 구할때는 sum(axis=1)


In [45]:
# 예제 DF 생성
#4행 8열의 데이터프레임 작성, 난수를 발생시키고
#0-9범위에서 매번 같은 난수 발생되어 반환되도록 설정
np.random.seed(1)
df2=pd.DataFrame(np.random.randint(10,size=(4,8)))
df2

0  1  2  3  4  5  6  7
0  5  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

In [46]:
# df2의 각 행의 합계 구하기
# 4행이므로 4개의 값을 시리즈로 반환
df2.sum(axis=1)

0    35
1    34
2    41
3    42
dtype: int64

In [47]:
# df2의 각 열의 합계 구하기
# 8열 이므로 8개의 값을 시리즈로 반환
df2.sum(axis=0)
df2.sum() # axis는 디폴트값이 0이므로 각 열의 합계는 생략가능

0    24
1    33
2    25
3    24
4    15
5    10
6     5
7    16
dtype: int64

0    24
1    33
2    25
3    24
4    15
5    10
6     5
7    16
dtype: int64

##### df의 기본 함수
- mean(axis=0/1)
- min(axis=0/1)
- max(axis=0/1)

In [48]:
# 예제 DF 확인
df2

0  1  2  3  4  5  6  7
0  5  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

In [49]:
df2.mean(axis=0) # 각 열의 평균
df2.mean(axis=1) # 각 행의 평균

0    6.00
1    8.25
2    6.25
3    6.00
4    3.75
5    2.50
6    1.25
7    4.00
dtype: float64

0    4.375
1    4.250
2    5.125
3    5.250
dtype: float64

In [50]:
df2.min(axis=0) # 각 열의 최소값
df2.max(axis=1) # 각 행의 최대값

0    4
1    7
2    2
3    4
4    0
5    0
6    0
7    1
dtype: int32

0    9
1    9
2    9
3    9
dtype: int32

In [51]:
df2['RowSum'] = df2.sum(axis=1) # RowSum 이라는 새로운 컬럼 추가
df2

0  1  2  3  4  5  6  7  RowSum
0  5  8  9  5  0  0  1  7      35
1  6  9  2  4  5  2  4  2      34
2  4  7  7  9  1  7  0  6      41
3  9  9  7  6  9  1  0  1      42

In [52]:
df2.loc['ColTotal'] = df2.sum(axis=0)
df2

0   1   2   3   4   5  6   7  RowSum
0          5   8   9   5   0   0  1   7      35
1          6   9   2   4   5   2  4   2      34
2          4   7   7   9   1   7  0   6      41
3          9   9   7   6   9   1  0   1      42
ColTotal  24  33  25  24  15  10  5  16     152

In [53]:
df2.sum(axis=1) # sum 함수 적용 시 raw data 인지 계산필드인지 확인해서 적용할 것

0            70
1            68
2            82
3            84
ColTotal    304
dtype: int64

### 행/열 삭제 - drop() 사용 예제
- df.drop('행이름',0) : 행삭제 
    - 행삭제 후 df로 결과를 반환
- df.drop('행이름',1) : 열 삭제
    - 행삭제 후 df로 결과를 반환
- 원본에 반영되지 않으므로  원본수정하려면 저장 해야 함

In [54]:
df2

0   1   2   3   4   5  6   7  RowSum
0          5   8   9   5   0   0  1   7      35
1          6   9   2   4   5   2  4   2      34
2          4   7   7   9   1   7  0   6      41
3          9   9   7   6   9   1  0   1      42
ColTotal  24  33  25  24  15  10  5  16     152

In [55]:
df2.drop('RowSum', axis=1)
df2.drop('RowSum', axis=1, inplace=True)
df2

0   1   2   3   4   5  6   7
0          5   8   9   5   0   0  1   7
1          6   9   2   4   5   2  4   2
2          4   7   7   9   1   7  0   6
3          9   9   7   6   9   1  0   1
ColTotal  24  33  25  24  15  10  5  16

0   1   2   3   4   5  6   7
0          5   8   9   5   0   0  1   7
1          6   9   2   4   5   2  4   2
2          4   7   7   9   1   7  0   6
3          9   9   7   6   9   1  0   1
ColTotal  24  33  25  24  15  10  5  16

In [56]:
df2.drop('ColTotal', axis=0)
df2.drop('ColTotal', axis=0, inplace=True)
df2

0  1  2  3  4  5  6  7
0  5  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

0  1  2  3  4  5  6  7
0  5  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

#### NaN 값 처리 함수
   - df.dropna(axis=0/1)
       - NaN값이 있는 열 또는 행을 삭제
       - 원본 반영되지 않음
       - 행/열 단위 삭제가 일어남
           - 결측치 수가 행이나 열단위로 상대적으로 많을 때 사용

   - df.fillna(0) 
       - NaN값을 정해진 숫자로 채움
           - 아주 중요한 컬럼이거나 결측치의 수가 상대적으로 적을 때 사용
           - 시계열 data(시간의 흐름에 따라 변화량을 나타내는 데이터)인 경우
               - 시계열 data는 결측치라하더라도 예측하기가 쉬움
               - ex) 오늘 시간별 날씨 data에서 오전 8시 데이터가 결측이면 7시나 9시 날씨 데이터로 채워서 사용가능
       - 원본 반영 되지 않음

In [57]:
# 연습을 위한 결측치 값 저장
df2.iloc[0,0] = np.nan
df2

0  1  2  3  4  5  6  7
0  NaN  8  9  5  0  0  1  7
1  6.0  9  2  4  5  2  4  2
2  4.0  7  7  9  1  7  0  6
3  9.0  9  7  6  9  1  0  1

In [58]:
# dropna() nan이 들어있는 행 삭제
df2.dropna(axis=0)

0  1  2  3  4  5  6  7
1  6.0  9  2  4  5  2  4  2
2  4.0  7  7  9  1  7  0  6
3  9.0  9  7  6  9  1  0  1

In [59]:
# dropna() nan이 들어있는 열 삭제
df2.dropna(axis=1)

1  2  3  4  5  6  7
0  8  9  5  0  0  1  7
1  9  2  4  5  2  4  2
2  7  7  9  1  7  0  6
3  9  7  6  9  1  0  1

In [60]:
df2 # df2의 결측치는 1개 => 결측치의 수가 적으므로 결측치를 임의의 data로 채워서 사용
# 보통 대표값인 평균값을 이용, 0이나 1도 이용
# 시계열인 경우 결측데이터의 시간적으로 얖이나 뒤 data를 이용하여 채움
# 정해진 값은 없으므로 최소값/최대값을 이용하기도 하고 다른 유효한 데이터를 이용해서 예측해서 채우기도 함
# 머신러닝 / 딥러닝 전처리에서 위 내용 다시 정리

0  1  2  3  4  5  6  7
0  NaN  8  9  5  0  0  1  7
1  6.0  9  2  4  5  2  4  2
2  4.0  7  7  9  1  7  0  6
3  9.0  9  7  6  9  1  0  1

In [61]:
df2.fillna(0) # 모든 NaN값은 0으로 채움

0  1  2  3  4  5  6  7
0  0.0  8  9  5  0  0  1  7
1  6.0  9  2  4  5  2  4  2
2  4.0  7  7  9  1  7  0  6
3  9.0  9  7  6  9  1  0  1

In [62]:
df2.fillna(df2[0].mean()) # df2의 0번 열의 평균값으로 채움

0  1  2  3  4  5  6  7
0  6.333333  8  9  5  0  0  1  7
1  6.000000  9  2  4  5  2  4  2
2  4.000000  7  7  9  1  7  0  6
3  9.000000  9  7  6  9  1  0  1

In [63]:
df2 # 원본반영되지 않음
df2.fillna(df2[0].mean(), inplace=True)  # 원본반영 파라미터
df2

0  1  2  3  4  5  6  7
0  NaN  8  9  5  0  0  1  7
1  6.0  9  2  4  5  2  4  2
2  4.0  7  7  9  1  7  0  6
3  9.0  9  7  6  9  1  0  1

0  1  2  3  4  5  6  7
0  6.333333  8  9  5  0  0  1  7
1  6.000000  9  2  4  5  2  4  2
2  4.000000  7  7  9  1  7  0  6
3  9.000000  9  7  6  9  1  0  1

In [65]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       4 non-null      float64
 1   1       4 non-null      int64  
 2   2       4 non-null      int64  
 3   3       4 non-null      int64  
 4   4       4 non-null      int64  
 5   5       4 non-null      int64  
 6   6       4 non-null      int64  
 7   7       4 non-null      int64  
dtypes: float64(1), int64(7)
memory usage: 288.0+ bytes


In [67]:
int(6.0)

6

In [69]:
# int(df2)
# TypeError: int() argument must be a string, a bytes-like object or a real number, not 'DataFrame'
# not 'DataFrame' DataFrame 은 2차원이므로 원소 1개로 변경하는 int() 적용 불가능

In [73]:
# df 내의 각 열이나 행 단위로 data type 변경 가능 (보통 열단위 변경)
df2[0].astype(int) # 원본 반영 되지 않음
df2

0    6
1    6
2    4
3    9
Name: 0, dtype: int32

0  1  2  3  4  5  6  7
0  6.333333  8  9  5  0  0  1  7
1  6.000000  9  2  4  5  2  4  2
2  4.000000  7  7  9  1  7  0  6
3  9.000000  9  7  6  9  1  0  1

In [74]:
df2.astype(int) # df의 value의 type을 변경하는 함수 => 이건 되네
# 원본에 반영되지 않음

0  1  2  3  4  5  6  7
0  6  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

In [75]:
df2

0  1  2  3  4  5  6  7
0  6.333333  8  9  5  0  0  1  7
1  6.000000  9  2  4  5  2  4  2
2  4.000000  7  7  9  1  7  0  6
3  9.000000  9  7  6  9  1  0  1

In [76]:
df2 = df2.astype(int) # 원본 반영
df2

0  1  2  3  4  5  6  7
0  6  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

In [78]:
df2.iloc[0,0] = np.nan
df2

0  1  2  3  4  5  6  7
0  NaN  8  9  5  0  0  1  7
1  6.0  9  2  4  5  2  4  2
2  4.0  7  7  9  1  7  0  6
3  9.0  9  7  6  9  1  0  1

In [82]:
# DataFrame은 chain 연산 가능
# df.연산함수() 해서 나온 결과에 이어서 연산함수 적용하는 것 : chain 연산
df2.fillna(0).astype(int).sum()

0    19
1    33
2    25
3    24
4    15
5    10
6     5
7    16
dtype: int64

### 열 또는 행에 동일한 연산 반복 적용할 때 : apply() 함수
- apply() 함수는 DataFrame의 행이나 열에 복잡한 연산을 vectorizing할 수 있게 해주는 함수로 매우 많이 활용되는 함수임
- 동일한 연산을 모든열에 혹은 모든 행에 반복 적용하고자 할때 사용

- apply(반복적용할 함수, axis=0/1)
    - 0 : 열마다 반복
    - 1 : 행마다 반복 
    - 생략시 기본값 : 0

In [83]:
#예제 df 생성
df3 = pd.DataFrame({
    'a':[1,3,4,3,4],
    'b':[2,3,1,4,5],
    'c':[1,5,2,4,4]
})
df3

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [84]:
# np.sum() 함수는 전달된 첫번째 인수 데이터들의 합산 결과를 반환
np.sum([1,2,3])

6

In [92]:
# df3의 각 열에  np.sum()함수를 적용하시오
# 개별 열 단위 적용
np.sum(df3['a'])
np.sum(df3['b'])
np.sum(df3['c'])

# 반복문을 이용
for i in ['a', 'b', 'c']:
    print(np.sum(df3[i]))
    
# np.sum() 함수를 DF의 각 열에 대해서 벡터화 연산하는 것이 목표
# apply 함수를 사용해서 np.sum() 함수를 df3의 각 열에 적용해서 연산을 진행하고 결과를 반환하는 코드
df3.apply(np.sum, axis=0)

15

15

16

15
15
16


a    15
b    15
c    16
dtype: int64

In [95]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [101]:
# titanic df의 alive, sex, class 열 각각에 대해서 value_counts() 함수를 적용한 결과를 확인하시오.
titanic[['alive','sex','class']].value_counts() # 모든 열 조합의 경우의 수를 따져 경우의 수마다 빈도 수 반환
titanic['alive'].value_counts() # 이렇게 각각 count가 들어가야되는데 => alive 열의 빈도수 반환 

titanic[['alive','sex','class']].apply(pd.value_counts, axis=0)

alive  sex     class 
no     male    Third     300
               Second     91
yes    female  First      91
no     male    First      77
       female  Third      72
yes    female  Third      72
               Second     70
       male    Third      47
               First      45
               Second     17
no     female  Second      6
               First       3
dtype: int64

no     549
yes    342
Name: alive, dtype: int64

alive    sex  class
First     NaN    NaN  216.0
Second    NaN    NaN  184.0
Third     NaN    NaN  491.0
female    NaN  314.0    NaN
male      NaN  577.0    NaN
no      549.0    NaN    NaN
yes     342.0    NaN    NaN

- 데이터프레임의 기본 집계함수(sum, min, max, mean 등)들은 행/열 단위 벡터화 연산을 수행함
    - apply() 함수를 사용할 필요가 없음

- 일반적으로 apply() 함수 사용은 복잡한 연산을 해결하기 위한 lambda 함수나 사용자 정의 함수를 각 열 또는 행에 일괄 적용시키기 위해 사용

**사용자 정의 함수를 apply() 파라미터로 사용하는 예제**

In [102]:
# 연습용 사용자 정의 함수

# 사용자로부터 시리즈를 전달받아(매개변수) 해당 시리즈의 최대값과 최소값의 차이를 계산해서 반환하는 함수 diff(x) 정의
def diff(x): # x는 시리즈 형태
    return x.max() - x.min()

In [104]:
# df3의 각 열에 대해 diff 함수를 적용시킨 결과를 확인하시오
diff(df3['a'])
diff(df3['b'])
diff(df3['c'])

3

4

4

In [103]:
# df3에 apply 함수를 적용시커 df3의 각 열에 대해 diff 함수를 적용시킨 결과 확인
df3.apply(diff, axis=0)

a    3
b    4
c    4
dtype: int64

##### 1회성함수 lambda 함수를 apply()에  사용하는 예제

In [105]:
# 사용자로부터 시리즈를 전달받아(매개변수) 해당 시리즈의 최대값과 최소값의 차이를 계산해서 반환하는 lambda 함수
(lambda x:x.max()-x.min())(df3['a'])

3

In [106]:
# 위 셀이서 생성한 lambda 함수에 대해 df3의 각 열 시리즈를 적용된 결과를 반환
df3.apply(lambda x:x.max()-x.min(), 0)

a    3
b    4
c    4
dtype: int64

In [107]:
# df3의 각 행에 대해 lambda 함수를 적용한 결과 
df3.apply(lambda x:x.max()-x.min(), 1)

0    1
1    2
2    3
3    1
4    1
dtype: int64

In [110]:
## df3 각 열에 대해 최대값과 최소값의 차이를 구하시오.
# apply 함수 사용하지 말 것
# 최대값과 최소값을 구하는 df의 함수는 벡터화 연산을 진행함
df3.max() - df3.min()

a    3
b    4
c    4
dtype: int64

In [112]:
# 첫번째 파라미터로 주어진 data 각각에 대해 제곱승 연산을 진행
np.square([1,2,3])
df3.apply(np.square,0)
df3.apply(np.square,1)
# apply()로 df의 행이나 열에 적용되어지는 함수가 행/열 집합이 아닌 요소 각각에 적용되는 함수라면 각 원소마다 함수를 적용시켜 줌
# axis 방향에 관계없이 동일한 결과가 나타남 => 행 / 열 단위 상관없이 같은 결과가 반환됨

array([1, 4, 9])

a   b   c
0   1   4   1
1   9   9  25
2  16   1   4
3   9  16  16
4  16  25  16

a   b   c
0   1   4   1
1   9   9  25
2  16   1   4
3   9  16  16
4  16  25  16

#### 데이터값을 카테고리 값으로 변환
- 값의 크기를 기준으로하여 카테고리 값으로 변환하고 싶을때
    - cut(data,bins,label)
        - 기준값을 사용자가 설정 함
        - data : 구간 나눌 실제 값, bins : 구간 경계값, label: 카테고리값
    - qcut(data,bins(구간 수),label)
        - 구간수를 설정함

In [114]:
# 구간을 나눌 실제 값 : 관측 데이터
# 데이터 값 0도 구간값으로 넣을 것의 조건을 설정하려면?
ages=[0,0.5,4,6,4,5,2,10,21,23,37,15,38,31,61,20,41,31,100]
ages

[0, 0.5, 4, 6, 4, 5, 2, 10, 21, 23, 37, 15, 38, 31, 61, 20, 41, 31, 100]

In [115]:
# data : 구간 나눌 실제 값, bis : 구간 경계값, label : 카테고리 값
data = ages

# 구간 경계값 = 사용자가 임의 설정
# 구간 최소값 < 구간 <= 구간 최대값
bins = [0,4,18,25,35,60,100]

# 각 구간의 이름 - labels => 카테고리명
# 구간 이름의 순서는 bins 구간 순서와 동일해야 함
labels = ['영유아', '미성년자', '청소년', '청년', '중년', '노년']

In [119]:
len(data)
cats = pd.cut(data, bins, labels=labels)
cats
type(cats)
cats[0]

19

[NaN, '영유아', '영유아', '미성년자', '영유아', ..., '노년', '청소년', '중년', '청년', '노년']
Length: 19
Categories (6, object): ['영유아' < '미성년자' < '청소년' < '청년' < '중년' < '노년']

pandas.core.arrays.categorical.Categorical

nan

In [120]:
# 구간 경계값 - 사용자가 임의 설정
# 구간 최소각 < 구간 <= 구간 최대값
# 0살도 구간값으로 포함하기 위해서는 첫번째 구간의 최소값을 0보다 작게 설정해야한다.
bins = [-1,4,18,25,35,60,100]
cats = pd.cut(data, bins, labels=labels)
cats

['영유아', '영유아', '영유아', '미성년자', '영유아', ..., '노년', '청소년', '중년', '청년', '노년']
Length: 19
Categories (6, object): ['영유아' < '미성년자' < '청소년' < '청년' < '중년' < '노년']

In [122]:
temp = pd.DataFrame({'나이': ages, '연령대': cats})
temp['연령대'].value_counts()

영유아     5
미성년자    4
청소년     3
중년      3
청년      2
노년      2
Name: 연령대, dtype: int64

##### Categorical 클래스 객체
- 카테고리명 속성 : Categorical.categories
- 코드 속성 : Categorical.codes 
    - 인코딩한 카테고리 값을 정수로 갖는다.

In [124]:
bins = [0,4,18,25,35,60,100]
cats = pd.cut(data, bins, labels=labels)
type(cats)

pandas.core.arrays.categorical.Categorical

In [125]:
# categories 속성 : 카테고리명 저장
cats.categories

Index(['영유아', '미성년자', '청소년', '청년', '중년', '노년'], dtype='object')

In [127]:
# codes : 인코딩된 결과값을 정수로 가지고 있음
cats.codes
# codes 값이 -1 이면 카테고리화 하지 못했다는 뜻(결측치) => 범주화 실패

array([-1,  0,  0,  1,  0,  1,  0,  1,  2,  2,  4,  1,  4,  3,  5,  2,  4,
        3,  5], dtype=int8)

##### 구간 경계선을 지정하지 않고 데이터 개수가 같도록 지정한 수의 구간으로 분할하기 :  qcut()  

- 형식 : pd.qcut(data,구간수,labels=[d1,d2....])
    
    
    - 예)1000개의 데이터를 4구간으로 나누려고 한다면
        - qcut 명령어를 사용 한 구간마다 250개씩 나누게 된다.
        - 예외)같은 숫자인 경우에는 같은 구간으로 처리한다.


In [128]:
# 랜덤정수 20개를 생성하고 생성된 정수를 4개의 구간으로 나누시오.

# 각 구간의 label은 Q1,Q2,Q3,Q4 로 설정하시오.

#랜덤정수 생성 : 범위 0-19, size =20
#seed 설정해서 재 실행해도 랜덤정수가 변하지 않도록 생성
np.random.seed(2)
data = np.random.randint(20, size=20)
data

array([ 8, 15, 13,  8, 11, 18, 11,  8,  7,  2, 17, 11, 15,  5,  7,  3,  6,
        4, 10, 11])

In [130]:
qcat = pd.qcut(data, 4, labels=['Q1','Q2','Q3','Q4'])
qcat

['Q2', 'Q4', 'Q4', 'Q2', 'Q3', ..., 'Q1', 'Q1', 'Q1', 'Q3', 'Q3']
Length: 20
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [131]:
np.sort(data)

array([ 2,  3,  4,  5,  6,  7,  7,  8,  8,  8, 10, 11, 11, 11, 11, 13, 15,
       15, 17, 18])

In [133]:
qcat.value_counts()

Q1    5
Q2    5
Q3    5
Q4    5
dtype: int64

### 인덱스 설정 함수
#### 데이터 프레임 인덱스 설정을 위해 set_index(), reset_index()
- set_index() : 기존 행 인덱스를 제거하고 데이터 열 중
하나를 인덱스로 설정해주는 함수
- reset_index() : 기존 행인덱스를 제거하고 기본인덱스로 변경
- 기본인덱스 : 0부터 1씩 증가하는 정수 인덱스
    - 따로 설정하지 않으면 기존 인덱스는 데이터열로 추가 됨

In [140]:
#예제 데이터프레임 생성
df3 = pd.DataFrame({
    'a':[1,3,4,3,4],
    'b':[2,3,1,4,5],
    'c':[1,5,2,4,4]
})
df3

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [141]:
df3.set_index('a') #df3 의 a열을 행 index로 설정
df3 # 원본 반영 안됨
df3.set_index('a', inplace=True)
df3

b  c
a      
1  2  1
3  3  5
4  1  2
3  4  4
4  5  4

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

b  c
a      
1  2  1
3  3  5
4  1  2
3  4  4
4  5  4

In [142]:
df3
# 아래 df를 확인하면 행 index가 중복되어 있음(3번 index, 4번 index)

b  c
a      
1  2  1
3  3  5
4  1  2
3  4  4
4  5  4

In [143]:
df3.loc[3]
# df는 index가 중복될 수 있음

b  c
a      
3  3  5
3  4  4

In [145]:
# index의 중복을 제거하기 위해 0 base index를 다시 생성
# reset_index()
df3.reset_index() # 기존 index는 컬럼 데이터로 추가됨, 원본반영되지 않음

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [146]:
# df3에 새로운 0 base index를 설정하고 기존 index는 제거
df3.reset_index(drop=True)

b  c
0  2  1
1  3  5
2  1  2
3  4  4
4  5  4

In [147]:
df3.reset_index(drop=True, inplace=True) # 원본 반영
df3

b  c
0  2  1
1  3  5
2  1  2
3  4  4
4  5  4

### index 명과 columns 명 변경(부분변경)
- rename(index={현재index:바꿀index}) : 행인덱스
- rename(columns={현재컬럼명:바꿀컬럼명}) : 컬럼명 변경

In [151]:
# 컬럼명 변경
df3.rename(columns={'b':'학생 수', 'c':'책상 수'}) # 원본 반영 안됨
df3
df3.rename(columns={'b':'학생 수', 'c':'책상 수'}, inplace=True) # 원본 반영

학생 수  책상 수
0     2     1
1     3     5
2     1     2
3     4     4
4     5     4

학생 수  책상 수
0     2     1
1     3     5
2     1     2
3     4     4
4     5     4

In [153]:
# index 명 변경
df3.rename(index={0:'1반',1:'2반'}) # 원본반영 안됨

학생 수  책상 수
1반     2     1
2반     3     5
2      1     2
3      4     4
4      5     4

### 리스트 내포 연산

#### 리스트 내포 for문의 일반 문법
- [표현식(연산식) for 항목 in 반복가능객체 if 조건문]
- if 조건문은 생략 가능하다.
- 반복가능객체 : 리스트, 튜플,딕셔너리,range()등

In [155]:
### 리스트 내포 for 문
a=[1,2,3,4] 
# 위 a 리스트의 각 원소에 2배한 원소값을 만들고 리스트로 저장하시오. 반복문을 사용할 것
# result =[2,4,6,8]

In [156]:
result = []
for num in a :
    result.append(num*2)
result    

[2, 4, 6, 8]

In [157]:
result = [num * 2 for num in a]
result

[2, 4, 6, 8]

In [ ]:
# 연습문제
# ['id_1','id_2','id_3','id_4'] 와 같은 리스트 요소를
# 내포 for문을 이용해서 생성후 리스트로 추가하시오.
